#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
input=${1:-"$script_dir/internal_cr_allowlist.tsv"}
v8_out=${2:-"$script_dir/../../../v8/v8_tizen.filter"}
node_out=${3:-"$script_dir/../../../third_party/electron_node/node.filter"}
node_nonstd_input=${4:-"$script_dir/node_nonstd_export_allowlist.tsv"}

fail() {
  echo "[FILTER-GEN-FAIL] $*" >&2
  exit 1
}

for tool in awk cmp cp dirname mkdir mktemp rm sha256sum sort wc; do
  command -v "$tool" >/dev/null || fail "missing tool: $tool"
done
[[ -f $input ]] || fail "missing input: $input"
[[ -f $node_nonstd_input ]] || fail "missing input: $node_nonstd_input"
[[ $(wc -l < "$input") -eq 34 ]] || fail "allowlist must contain 34 rows"
awk -F '\t' 'NF != 3 || $1 !~ /^lib(v8|node)\.so$/ || $2 !~ /^_Z/ { bad++ }
  $2 !~ /NSt4__Cr/ { bad++ }
  { key=$1 SUBSEP $2; if (seen[key]++) bad++ }
  END { exit bad != 0 }' "$input" || fail "invalid or duplicate allowlist row"
[[ $(awk -F '\t' '$1=="libv8.so" {n++} END{print n+0}' "$input") -eq 27 ]] ||
  fail "libv8 allowlist count must be 27"
[[ $(awk -F '\t' '$1=="libnode.so" {n++} END{print n+0}' "$input") -eq 7 ]] ||
  fail "libnode allowlist count must be 7"
[[ $(wc -l < "$node_nonstd_input") -eq 354 ]] ||
  fail "libnode stable non-STL allowlist count must be 354"
awk -F '\t' 'NF != 2 || $1 !~ /^_Z/ || $1 == $2 || $2 ~ /std::/ {bad++}
  {if (seen[$1]++) bad++} END {exit bad != 0}' "$node_nonstd_input" ||
  fail "invalid, duplicate, unknown, or STL-carrying libnode stable symbol"

mkdir -p "$(dirname "$v8_out")" "$(dirname "$node_out")"
tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT

{
  echo '# Generated by tizen_src/build/abi/generate_libcxx_export_filters.sh.'
  echo '# Do not edit; edit the ABI allowlist TSV files and regenerate.'
  echo '{'
  echo '  global:'
  awk -F '\t' '$1=="libv8.so" {print "    " $2 ";"}' "$input" | LC_ALL=C sort
  echo '  local:'
  echo '    *NSt4__Cr*;'
  echo '    *NSt3__1*;'
  echo '};'
} > "$tmp_dir/v8.filter"

{
  echo '# Generated by tizen_src/build/abi/generate_libcxx_export_filters.sh.'
  echo '# Do not edit; edit the ABI allowlist TSV files and regenerate.'
  echo '{'
  echo '  global:'
  {
    awk -F '\t' '$1=="libnode.so" {print "    " $2 ";"}' "$input"
    awk -F '\t' '{print "    " $1 ";"}' "$node_nonstd_input"
  } | LC_ALL=C sort -u
  echo '    node_module_register;'
  echo '    uv_*;'
  echo '  local:'
  echo '    *;'
  echo '};'
} > "$tmp_dir/node.filter"

install_if_changed() {
  local generated=$1 destination=$2
  if [[ -f $destination ]] && cmp -s "$generated" "$destination"; then
    return
  fi
  cp "$generated" "$destination"
}

install_if_changed "$tmp_dir/v8.filter" "$v8_out"
install_if_changed "$tmp_dir/node.filter" "$node_out"

echo "[FILTER-GEN-OK] v8_cr=27 node_cr=7 node_nonstd=354 total_cxx=388"
sha256sum "$input" "$node_nonstd_input" "$v8_out" "$node_out"
