[general]
profile = profile.tizen_unified_standard
buildroot = ~/GBS-ROOT-TOOLCHAIN-GCC-PATCHES2

[profile.tizen_unified_standard]
repos = repo.base-standard, repo.unified-standard

[repo.base-standard]
url=https://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Base/reference/repos/standard/packages/
# url=https://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Base/tizen-base_20260219.223706/repos/standard/packages/
# url=http://download.tizen.org/SBS/TIZEN/Tizen/Tizen-Base-Dev/tizen-base-dev_20260325.020522/repos/standard/packages/
# url=http://109.123.100.71/test_files/gcc/tizen-base-dev_20260325.020522/repos/standard/packages

[repo.unified-standard]
url=https://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Unified/reference/repos/standard/packages/
# url=https://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Unified/tizen-unified_20260309.210600/repos/standard/packages/
